### ISSUE TITLE
User model needs to be updated

### ISSUE THREAD

**Issue by Fitog4** [lauracoding7/shortcut#6]
In schema.rb line 73, I see that the User currently has a  "commute_area_center" field, which is not ok, because we need it to be an address, a longitude and a latitude.
-     The field "commute_area_center" should be eliminated and instead we should have the three following fields:
-     "commute_area_address"
-     "commute_area_latitude"
-     "commute_area_longitude"

Could you submit a new pull request with your proposed migration file? 
Thanks for taking care of this!

**Comment by GuitK** [comment]
Jonah fixed the issue
